import { lstat, readFile, unlink, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createInterface } from 'node:readline/promises'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const envFile = resolve(repositoryRoot, 'apps/www/.env')
const manifestFile = resolve(repositoryRoot, 'apps/www/public/manifest.json')
const argumentsList = process.argv.slice(2)
const supportedArguments = new Set(['--', '--force', '--help'])
const unknownArguments = argumentsList.filter((argument) => !supportedArguments.has(argument))
const force = argumentsList.includes('--force')

if (unknownArguments.length > 0) {
  console.error(`Unknown argument(s): ${unknownArguments.join(', ')}`)
  console.error('Usage: pnpm scaffold:init [--force]')
  process.exit(1)
}

if (argumentsList.includes('--help')) {
  console.log(`Usage: pnpm scaffold:init [--force]

Create apps/www/.env and synchronize public manifest metadata.

Options:
  --force  Replace an existing apps/www/.env
  --help   Show this help message`)
  process.exit(0)
}

const initialEnvStatus = await getFileStatus(envFile)
assertRegularFile(initialEnvStatus, 'apps/www/.env')

if (!force && initialEnvStatus) {
  console.error('apps/www/.env already exists. Re-run with --force only if you intend to replace it.')
  process.exit(1)
}

const manifestState = await readManifest()
const readline = createInterface({ input: process.stdin, output: process.stdout })

try {
  console.log('Configure the public metadata for this starter. Every VITE_* value is exposed to the browser.')

  const values = {
    VITE_SITE_URL: await ask('Site URL', 'http://localhost:3000', validateSiteOrigin),
    VITE_SITE_NAME: await ask('Site name', 'TanStack Starter', validateText(80)),
    VITE_SITE_DESCRIPTION: await ask(
      'Site description',
      'A production-minded TanStack Start application starter',
      validateText(200),
    ),
    VITE_SITE_AUTHOR: await ask('Author (optional)', '', validateText(100)),
    VITE_HOMEPAGE_URL: await ask('Homepage URL (optional)', '', validateOptionalHttpUrl),
    VITE_GITHUB_URL: await ask('GitHub URL (optional)', '', validateOptionalHttpUrl),
    VITE_TWITTER_HANDLE: await ask('X/Twitter handle (optional)', '', validateTwitterHandle),
    VITE_GA_ID: await ask('Google Analytics GA4 ID (optional)', '', validateGaId),
  }

  const contents = [
    '# Generated by `pnpm scaffold:init`.',
    '# All VITE_* variables are public and must never contain secrets.',
    ...Object.entries(values).map(([key, value]) => `${key}=${quoteDotenv(value)}`),
    '',
  ].join('\n')
  const manifest = manifestState.value
  const manifestContents = `${JSON.stringify(
    {
      ...manifest,
      short_name: values.VITE_SITE_NAME,
      name: values.VITE_SITE_NAME,
      description: values.VITE_SITE_DESCRIPTION,
    },
    null,
    2,
  )}\n`

  const currentEnvStatus = await getFileStatus(envFile)
  assertRegularFile(currentEnvStatus, 'apps/www/.env')
  if (!force && currentEnvStatus) {
    throw new Error('apps/www/.env was created while initialization was running; refusing to overwrite it')
  }

  const previousEnvContents = currentEnvStatus ? await readFile(envFile, 'utf8') : undefined

  try {
    await writeFile(manifestFile, manifestContents, 'utf8')
    await writeFile(envFile, contents, { encoding: 'utf8', flag: currentEnvStatus ? 'w' : 'wx' })
  } catch (error) {
    const rollbackErrors = []

    try {
      await writeFile(manifestFile, manifestState.contents, 'utf8')
    } catch (rollbackError) {
      rollbackErrors.push(rollbackError)
    }

    try {
      if (previousEnvContents !== undefined) {
        await writeFile(envFile, previousEnvContents, 'utf8')
      } else if (error?.code !== 'EEXIST') {
        await unlink(envFile)
      }
    } catch (rollbackError) {
      if (rollbackError?.code !== 'ENOENT') rollbackErrors.push(rollbackError)
    }

    if (rollbackErrors.length > 0) {
      throw new AggregateError([error, ...rollbackErrors], 'Initialization failed and rollback was incomplete')
    }
    throw error
  }
  console.log('Created apps/www/.env and synchronized public/manifest.json metadata. Replace the icons as needed.')
} finally {
  readline.close()
}

async function ask(label, defaultValue, validate) {
  while (true) {
    const suffix = defaultValue ? ` (${defaultValue})` : ''
    const answer = (await readline.question(`${label}${suffix}: `)).trim() || defaultValue
    const error = validate(answer)

    if (!error) return answer
    console.error(error)
  }
}

function validateHttpUrl(value) {
  try {
    const url = new URL(value)
    if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) {
      return 'Enter an http(s) URL without embedded credentials.'
    }
  } catch {
    return 'Enter a valid absolute URL.'
  }
}

function validateOptionalHttpUrl(value) {
  return value ? validateHttpUrl(value) : undefined
}

function validateSiteOrigin(value) {
  const urlError = validateHttpUrl(value)
  if (urlError) return urlError

  const url = new URL(value)
  if (url.pathname !== '/' || url.search || url.hash) {
    return 'Enter only the site origin, without a path, query, or fragment.'
  }
}

function validateText(maxLength) {
  return (value) => {
    if (/[\r\n]/.test(value)) return 'Use a single-line value.'
    if (value.length > maxLength) return `Use no more than ${maxLength} characters.`
  }
}

function validateTwitterHandle(value) {
  if (!value || /^@?[A-Za-z0-9_]{1,15}$/.test(value)) return undefined
  return 'Use a valid X/Twitter handle (up to 15 letters, numbers, or underscores).'
}

function validateGaId(value) {
  if (!value || /^G-[A-Z0-9]+$/.test(value)) return undefined
  return 'Use a valid GA4 measurement ID such as G-ABC123DEF4.'
}

function quoteDotenv(value) {
  return JSON.stringify(value)
}

async function getFileStatus(path) {
  try {
    return await lstat(path)
  } catch (error) {
    if (error?.code === 'ENOENT') return undefined
    throw error
  }
}

function assertRegularFile(status, label) {
  if (status && (!status.isFile() || status.isSymbolicLink())) {
    throw new Error(`${label} must be a regular file; symbolic links and special files are refused`)
  }
}

async function readManifest() {
  const status = await getFileStatus(manifestFile)
  assertRegularFile(status, 'apps/www/public/manifest.json')
  if (!status) throw new Error('apps/www/public/manifest.json is missing')

  const contents = await readFile(manifestFile, 'utf8')
  const value = JSON.parse(contents)
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('apps/www/public/manifest.json must contain a JSON object')
  }
  return { contents, value }
}
